/*
Given: A positive integer n (3≤n≤10000).
Return: The number of internal nodes of any unrooted binary tree having n leaves.

In an unrooted binary tree, all leaves have degree one and all internal nodes have degree three.

The smallest possible unrooted binary tree has n=4 leaf nodes and 2 internal nodes:


\    /
 ----
/    \

As we add another internal node (with two children) the number of leaf nodes obviously doubles. 

*/



